# Change these first
owner: BQA-FAE
repo: benqservers 
user-agent: BQA-FAE
sites:
  - name: BenQ AMS
    url: https://ams.benq.com/#/
  - name: BenQ IAM
    url: https://iam.benq.com/
  - name: BenQ DMS
    url: https://dms.benq.com/#/
    icon: https://dms.benq.com/client/dms_logo.svg    
  - name: BenQ X-Sign Broadcast
    url: https://x-signbroadcast.benq.com/
  - name: BenQ Service Portal
    url: https://service-portal.benq.com/
  - name: EZWrite IoT
    url: https://ezwriteupload-eu.s3.eu-central-1.amazonaws.com/
    check: tcp-ping
    port: 443
  - name: EZWrite Cognito
    url: https://cognito-identity.eu-central-1.amazonaws.com/
    check: tcp-ping
    port: 443
  - name: EZWrite S3
    url: https://benq-ezwrite-eu.s3.eu-central-1.amazonaws.com
    check: tcp-ping
    port: 443
  - name: EZWrite SNS
    url: https://sns.eu-central-1.amazonaws.com
    check: tcp-ping
    port: 443
  - name: EZWrite SQS
    url: https://sqs.eu-central-1.amazonaws.com
    check: tcp-ping
    port: 443
  - name: EZWrite Portal
    url: https://ezwrite6.benq.com
    check: tcp-ping
    port: 443
  - name: EZW6 API
    url: https://ezwrite6-api.benq.com
    check: tcp-ping
    port: 443
  - name: EZ5 API
    url: https://ezwrite.benq.com
    check: tcp-ping
    port: 443
  - name: Matomo
    url: https://matomo.benq.com
    check: tcp-ping
    port: 443
  - name: EZ5/EZ6 apk OTA URL
    url: https://d2fqxlpnusiysx.cloudfront.net
    check: tcp-ping
    port: 443
  - name: EZ5 QR Code Sharin
    url: https://ezwriteupload.s3-ap-northeast-1.amazonaws.com
    check: tcp-ping
    port: 443
  - name: EZ5 Collab Server
    url: https://ezwrite-relay.benq.com/
    check: tcp-ping
    port: 443
  - name: EZWrite APK Download Server
    url: http://qspublic.s3.amazonaws.com
    check: tcp-ping
    port: 80
  - name: EZWrite APK Download Server 2
    url: http://qspublic.s3.ap-southeast-1.amazonaws.com
    check: tcp-ping
    port: 80
  - name: EZWrite OTA File Server
    url: https://qspublic.s3-ap-southeast-1.amazonaws.com/
    check: tcp-ping
    port: 443
  - name: BenQ FW API Server
    url: http://vod.benq.com/tvservice_api/api/response.php
    check: tcp-ping
    port: 80
  - name: FW OTA Image Server
    url: https://d3bx1fc1zkxy8q.cloudfront.net
    check: tcp-ping
    port: 443
  - name: FW OTA Update .XML
    url: https://donglefw.s3-ap-northeast-1.amazonaws.com/
    check: tcp-ping
    port: 443
  - name: FW QOTA API Server
    url: https://qotaapi.benq.com/api/v2/
    check: tcp-ping
    port: 443
  - name: FW Self-update API Server
    url: https://vod.benq.com
    check: tcp-ping
    port: 443
  - name: Firebase API Server
    url: https://benqqota.firebaseio.com
    check: tcp-ping
    port: 443
  - name: OTA Pkg and Release note
    url: https://d1m7bten765ify.cloudfront.net
    check: tcp-ping
    port: 443
  - name: AMS API
    url: https://ams.benq.com/api/*
    check: tcp-ping
    port: 443
  - name: Dropbox API
    url: https://api.dropboxapi.com
    check: tcp-ping
    port: 443
  - name: Register InstaQShare
    url: http://h1.ee-share.com/+B19B2:B38
    check: tcp-ping
    port: 443
  - name: Load BenQ Suggest
    url: http://vod.benq.com/suggest/public/
    check: tcp-ping
    port: 80
  - name: Easy WW API Server
    url: https://smartdms.benq.com/ESApi/public
    check: tcp-ping
    port: 443
  - name: Easy WW Relay Server
    url: http://relaysmartdms.benq.com:443
    check: tcp-ping
    port: 443
  - name: Easy CN API Server
    url: https://smartdms.benq.com.cn/ESApi/public
    check: tcp-ping
    port: 443
  - name: Easy CN Relay Server
    url: http://relaysmartdms.benq.com.cn:443
    check: tcp-ping
    port: 443
  - name: WW X-sign Cloud Server (maintaining connection)
    url: https://Relay.benq.com
    check: tcp-ping
    port: 443
  - name: WW X-sign Cloud Server (API Service)
    url: https://Apiservice.benq.com
    check: tcp-ping
    port: 443
  - name: WW X-sign Cloud Server (Manager connection)
    url: https://X-Sign.benq.com
    check: tcp-ping
    port: 443
  - name: WW X-sign Cloud Server (Player Logs)
    url: https://logapiservice.benq.com
    check: tcp-ping
    port: 443
  - name: WW X-sign Cloud Server (BDP/Archive)
    url: https://xsignbdp-eu.s3.eu-central-1.amazonaws.com
    check: tcp-ping
    port: 443
  - name: WW X-sign Cloud Server (Get Weather)
    url: https://sa900-api.elasticbeanstalk.com
    check: tcp-ping
    port: 443
  - name: Openweather
    url: https://api.openweathermap.org
    check: tcp-ping
    port: 443
  - name: Get Device JSON (DMS Cloud)
    url: http://staging2.benq.com
    check: tcp-ping
    port: 443
  - name: DMS MQTT Connection 
    url: https://dms-relay.benq.com
    check: tcp-ping
    port: 443
  - name: MDA Command Data (DMS Cloud & Local) 1
    url: https://cmota.s3.amazonaws.com
    check: tcp-ping
    port: 443
  - name: MDA Command Data (DMS Cloud & Local) 2
    url: https://cmota.s3.ap-northeast-1.amazonaws.com
    check: tcp-ping
    port: 443
  - name: Verify/Release Key (DMS Local)
    url: https://dsdownload.benq.com
    check: tcp-ping
    port: 443
  - name: AWS IoT Service for MQTT (DMS Cloud)
    url: apexd90h2t5wg-ats.iot.eu-central-1.amazonaws.com 
    check: tcp-ping
    port: 443
  - name: AWS IoT Service for MQTT (DMS Local)
    url: apexd90h2t5wg-ats.iot.eu-central-1.amazonaws.com 
    check: tcp-ping
    port: 443
  - name: DMS Firewall
    url: https://benq-dms-eu.s3.eu-central-1.amazonaws.com
    check: tcp-ping
    port: 443


assignees: 
  - shelwong
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  favicon: https://raw.githubusercontent.com/BQA-FAE/benqservers/master/assets/favicon.ico
  
  baseUrl: /benqservers

  links:
    - rel: stylesheet
      href: https://cdn.statically.io/gh/BQA-FAE/benqservers/09f7a419/assets/benq.css
      
  logoUrl: https://raw.githubusercontent.com/BQA-FAE/benqservers/master/assets/bqeLogo.png
  name: Servers Status
  introTitle: "**BenQ Education** Servers"
  introMessage: See the status of the BenQ services in North America
  
  navbar:
    - title: Status
      href: https://bqa-fae.github.io/benqservers/
    - title: Submit Ticket
      href: https://www.benq.com/en-us/support/contact-us.html
    - title: BenQ Home
      href: https://www.benq.com/en-us/education.html  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
