# Change these first
owner: BQA-FAE
repo: benqservers 
user-agent: BQA-FAE
sites:
  - name: BenQ AMS
    url: https://ams.benq.com/#/
  - name: BenQ IAM
    url: https://iam.benq.com/
  - name: BenQ DMS
    url: https://dms.benq.com/#/
    icon: https://dms.benq.com/client/dms_logo.svg    
  - name: BenQ X-Sign Broadcast
    url: https://x-signbroadcast.benq.com/
  - name: BenQ Service Portal
    url: https://service-portal.benq.com/login
  - name: SheldonTest
    url: https://shelwong.github.io/MyWebsite/

assignees: 
  - shelwong
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  favicon: https://raw.githubusercontent.com/BQA-FAE/benqservers/master/assets/favicon.ico
  
  baseUrl: /benqservers

  links:
    - rel: stylesheet
      href: https://cdn.statically.io/gh/BQA-FAE/benqservers/f0196815/assets/benq.css
      
  logoUrl: https://raw.githubusercontent.com/BQA-FAE/benqservers/master/assets/bqeLogo.png
  name: Servers Status
  introTitle: "**BenQ Education** Servers"
  introMessage: See the status of the BenQ services in North America
  
  navbar:
    - title: Status
      href: https://bqa-fae.github.io/benqservers/
    - title: Submit Ticket
      href: https://www.benq.com/en-us/support/contact-us.html
    - title: BenQ Home
      href: https://www.benq.com/en-us/education.html
    - title: TestSite
      href: https://shelwong.github.io/MyWebsite/index.html
  

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
